#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Tutorial
  # forward declarations
  class Person < ::ProtocolBuffers::Message; end
  class AddressBook < ::ProtocolBuffers::Message; end

  class Person < ::ProtocolBuffers::Message
    # forward declarations
    class PhoneNumber < ::ProtocolBuffers::Message; end

    # enums
    module PhoneType
      include ::ProtocolBuffers::Enum

      set_fully_qualified_name "tutorial.Person.PhoneType"

      MOBILE = 0
      HOME = 1
      WORK = 2
    end

    set_fully_qualified_name "tutorial.Person"

    # nested messages
    class PhoneNumber < ::ProtocolBuffers::Message
      set_fully_qualified_name "tutorial.Person.PhoneNumber"

      required :string, :number, 1
      optional ::Tutorial::Person::PhoneType, :type, 2, :default => ::Tutorial::Person::PhoneType::HOME
    end

    required :string, :name, 1
    required :int32, :id, 2
    optional :string, :email, 3
    repeated ::Tutorial::Person::PhoneNumber, :phones, 4
  end

  class AddressBook < ::ProtocolBuffers::Message
    set_fully_qualified_name "tutorial.AddressBook"

    repeated ::Tutorial::Person, :people, 1
  end

end